spring:
  devtools:
    livereload:
      enabled: false
  application:
    name: pefint
  datasource:
    url: jdbc:mysql://localhost:3306/pefint?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: pefint
    password: pefint123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop  #프로젝트 처음 실행
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    org,springframework.security: debug

jwt:
  secret: xAj34kL!92mv@Tqoe5N8y#Kj72DpAqLopCczmnnQQkQ=